/**
 * Auto-generated at build time.
 * Do NOT edit this file manually.
 */
window.__BUILD_VER = "v20260226-2330";
window.__BUILD_ASSETS = {"css": ["/assets/css/theme.tokens.v1.20260226.css", "/assets/css/vvip-luxe.v75.css", "/assets/css/vvip-hub.v85.css", "/assets/css/patch.v100.premiumdash.20260222.css", "/assets/css/pro-suite.v2.css", "/assets/css/typography.premium.v2.css", "/assets/css/patch.v101.contrast.20260226.css"], "js": ["/assets/js/ui.fix.v1.20260226.js", "/assets/js/ui.guard.v1.20260226.js", "/assets/js/vvip-global.v75.js", "/assets/js/j.searchtyping.v83.20260219.js", "/assets/js/pro-suite.v2.js"]};
